#ifndef __led_task_H    // header files should include guards
#define __led_task_H

#include "cmsis_os.h"

// Alternate Mode
//#define LD1_GPIO_PORT (GPIOA)
//#define LD1_GPIO_PIN (GPIO_PIN_5)

#define LD1_GPIO_PORT (GPIOB)
#define LD1_GPIO_PIN (GPIO_PIN_0)

#define LD2_GPIO_PORT (GPIOE)
#define LD2_GPIO_PIN (GPIO_PIN_1)

#define LD3_GPIO_PORT (GPIOB)
#define LD3_GPIO_PIN (GPIO_PIN_14)

typedef struct {
    int id;
    TaskHandle_t handle;  // generated by FreeRTOS, saved for later use (task synchronization, etc.)
    char task_name[16];
    
} LED_PARAMS_t;

extern LED_PARAMS_t led_params[2]; // defined here, allocated in led_task.c

void led_toggle(int id);
void led_task(void *parameters);
void led_task_init(int id, char *task_name);

#endif
