#ifndef __STEPPER_DRIVER_H    // header files should include guards
#define __STEPPER_DRIVER_H

#include "cmsis_os.h"
#include "stm32h743xx.h"
#include "x_nucleo_ihmxx.h"
#include "l6474.h"
#include <stdbool.h>
#include "ControlMessages.h"


#define STEPPER_NUM (3)
#define STEPPER_TASK_PRIORITY (6)
#define STEPPER_TASK_STACK (1024)

typedef struct {
    int id;
    TaskHandle_t handle;  // generated by FreeRTOS, saved for later use (task synchronization, etc.)
    
    int32_t pos;
    uint32_t speedMax;
    uint32_t speedMin;
    uint16_t accMax;
    uint16_t accMin;    
    
} STEPPER_PARAMS_t;




// Task Related functions
void StepperTask(void *parameters);
void StepperTaskInit(void);

// Public functions
void StepperClearMovements(void);
bool StepperAddMovement(uint8_t stepper, MTR_MVMNT mvmnt);
bool StepperMvmntFinished(void);
bool StepperMvmntStart(void);

// Private Functions
void Stepper_Error_Handler(uint16_t error);

#endif
